import NewNavbar from "@/components/NavBar/NavBar";
import NewFooter from "@/components/Footer/NewFooter";
import "./globals.css";

export const metadata = {
  title: "TEDxNTUA 2024",
  description:
    "Generated by TEDxNTUA2024-IT, tedxntua 2024, TEDX NTUA 2024, TEDxNTUA 2024, TEDxNTUA",
  icons: [
    {
      rel: "icon",
      type: "image/png",
      sizes: "32x32",
      url: "./favicons/favicon-32x32.png",
    },
    {
      rel: "icon",
      type: "image/png",
      sizes: "16x16",
      url: "./favicons/favicon-16x16.png",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundImage: `url('./background/background-laptop-new.jpg')`,
          backgroundAttachment: "fixed",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
        }}
        className="font-[aestheticRegular]"
      >
        <NewNavbar />

        {children}
        <NewFooter />
      </body>
    </html>
  );
}
